schema_version = "1.0.0"

id = "point_cloud_io"
version = "0.2.0"
name = "Point Cloud I/O"
tagline = "Import and export E57 and PLY point cloud files"
maintainer = "Sławomir Sobczak, Studio Medio <studiomedio.com@gmail.com>"
type = "add-on"

blender_version_min = "5.0.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 Sławomir Sobczak", "2026 Studio Medio"]
website = "https://github.com/studiomedio/blender-point-cloud-io"
tags = ["Import-Export"]

wheels = [
    "./wheels/pyquaternion-0.9.9-py3-none-any.whl",
    "./wheels/pye57-0.4.19-cp313-cp313-macosx_11_0_arm64.whl",
    "./wheels/pye57-0.4.19-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
    "./wheels/pye57-0.4.19-cp313-cp313-win_amd64.whl",
    "./wheels/laspy-2.7.0-py3-none-any.whl",
    "./wheels/lazrs-0.8.1-cp313-cp313-macosx_11_0_arm64.whl",
    "./wheels/lazrs-0.8.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/lazrs-0.8.1-cp313-cp313-win_amd64.whl",
]

[permissions]
files = "Read and write point cloud files on disk"
